version: '3.7'
services:
    web:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: php8.0
      volumes: 
        - ./:/var/www/html/
      ports:
        - 8000:80
    db:
      container_name: mysql8
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ad_handler_app
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - 6033:3306
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: root
      ports:
        - "9000:80"
